repository:
  image: mattgruter/artifactory
  volumes:
    - data/artifactory/data:/artifactory/data
    - data/artifactory/logs:/artifactory/logs
  ports:
    - "18080:8080"
goserver:
  image: gocd/gocd-server
  volumes_from:
    - godata
  ports:
    - "28153:8153"
  environment:  
    - AGENT_KEY=388b633a88de126531afa41eff9aa69e
godata:
  build: gocd-data
goagent:
# Build Localy
  build: go-agent
# Use prebuilt
#  image: sennerholm/gocd-agent
  volumes:
    - data/go-agent:/root/.docker
  links:
    - repository
    - goserver
  environment:  
    - DOCKER_HOST
    - DOCKER_TLS_VERIFY
