# From: https://github.com/mitchellh/vagrant/issues/3726
Vagrant.configure("2") do |config|
  config.vm.box = "mitchellh/boot2docker"

  # All port forwards for docker containers need to be added here
  config.vm.network "forwarded_port", guest: 28153, host: 28153

  config.vm.provider "virtualbox" do |v|
    # On VirtualBox, we don't have guest additions or a functional vboxsf
    # in TinyCore Linux, so tell Vagrant that so it can be smarter.
    v.check_guest_additions = false
    v.functional_vboxsf     = false
    v.customize ["modifyvm", :id, "--memory", "4096"]
  end

  ["vmware_fusion", "vmware_workstation"].each do |vmware|
    config.vm.provider vmware do |v|
      if v.respond_to?(:functional_hgfs=)
        v.functional_hgfs = false
      end
    end
  end

  # b2d doesn't support NFS
  config.nfs.functional = false
end
