# From: https://github.com/mitchellh/vagrant/issues/3726
Vagrant.configure("2") do |config|
  config.vm.box = "mitchellh/boot2docker"

  # All port forwards for docker containers need to be added here
  config.vm.network "forwarded_port", guest: 28153, host: 28153 #Go
  config.vm.network "forwarded_port", guest: 80, host: 8080 #Proxy, not configured yet
  config.vm.network "forwarded_port", guest: 18080, host: 18080 #artifactory
  config.vm.network "forwarded_port", guest: 28080, host: 28080 #doodleshop autosmall
  config.vm.network "forwarded_port", guest: 38080, host: 38080 #doodleshop autolarge
  config.vm.network "forwarded_port", guest: 48080, host: 48080 #doodleshop man
  config.vm.network "forwarded_port", guest: 58080, host: 58080 #doodleshop prod
  

  config.vm.provider "virtualbox" do |v|
    # On VirtualBox, we don't have guest additions or a functional vboxsf
    # in TinyCore Linux, so tell Vagrant that so it can be smarter.
    v.check_guest_additions = false
    v.functional_vboxsf     = false
    v.customize ["modifyvm", :id, "--memory", "4096"]
  end

  ["vmware_fusion", "vmware_workstation"].each do |vmware|
    config.vm.provider vmware do |v|
      if v.respond_to?(:functional_hgfs=)
        v.functional_hgfs = false
      end
    end
  end

  # b2d doesn't support NFS
  config.nfs.functional = false
end
